name: Codacy Analysis 

on:
  workflow_call:

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Export Codacy token
        run: |
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      
      - name: Run Codacy Coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with: 
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: .coverage/lcov.info
          language: cpp
